package com.example.sqllearning.dao;

import com.example.sqllearning.vo.mybatis.ArticleT;
import com.example.sqllearning.vo.mybatis.StuTeaT;
import java.util.List;
import org.springframework.stereotype.Component;

@Component
public interface TeacherTMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_t
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_t
     *
     * @mbggenerated
     */
    int insert(ArticleT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_t
     *
     * @mbggenerated
     */
    ArticleT selectByPrimaryKey(String articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_t
     *
     * @mbggenerated
     */
    List<ArticleT> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ArticleT record);

    List<StuTeaT> selectStuTea(List<String> students);
}