package ink.fujisann.learning.code.dao;

import ink.fujisann.learning.code.mybatis.ArticleT;

import java.util.List;

//@Component
public interface ArticleTMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_t
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_t
     *
     * @mbggenerated
     */
    int insert(ArticleT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_t
     *
     * @mbggenerated
     */
    ArticleT selectByPrimaryKey(String articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_t
     *
     * @mbggenerated
     */
    List<ArticleT> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ArticleT record);
}