package ink.fujisann.learning.code.dao;

import ink.fujisann.learning.code.vo.mybatis.TourDiaryT;

import java.util.List;

public interface TourDiaryTMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tour_diary_t
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String diaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tour_diary_t
     *
     * @mbggenerated
     */
    int insert(TourDiaryT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tour_diary_t
     *
     * @mbggenerated
     */
    TourDiaryT selectByPrimaryKey(String diaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tour_diary_t
     *
     * @mbggenerated
     */
    List<TourDiaryT> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tour_diary_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TourDiaryT record);
}