package ink.fujisann.learning.code.pojo.mybatis;

import java.util.Date;

public class TourDiaryT {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour_diary_t.diary_id
     *
     * @mbggenerated
     */
    private String diaryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour_diary_t.diary_date
     *
     * @mbggenerated
     */
    private Date diaryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour_diary_t.article_id
     *
     * @mbggenerated
     */
    private String articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour_diary_t.diary_level
     *
     * @mbggenerated
     */
    private Integer diaryLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour_diary_t.diary_title
     *
     * @mbggenerated
     */
    private String diaryTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour_diary_t.diary_city
     *
     * @mbggenerated
     */
    private String diaryCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour_diary_t.diary_province
     *
     * @mbggenerated
     */
    private String diaryProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour_diary_t.dairy_country
     *
     * @mbggenerated
     */
    private String dairyCountry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour_diary_t.diary_picture_path
     *
     * @mbggenerated
     */
    private String diaryPicturePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour_diary_t.diary_picture_name
     *
     * @mbggenerated
     */
    private String diaryPictureName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour_diary_t.diary_id
     *
     * @return the value of tour_diary_t.diary_id
     *
     * @mbggenerated
     */
    public String getDiaryId() {
        return diaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour_diary_t.diary_id
     *
     * @param diaryId the value for tour_diary_t.diary_id
     *
     * @mbggenerated
     */
    public void setDiaryId(String diaryId) {
        this.diaryId = diaryId == null ? null : diaryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour_diary_t.diary_date
     *
     * @return the value of tour_diary_t.diary_date
     *
     * @mbggenerated
     */
    public Date getDiaryDate() {
        return diaryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour_diary_t.diary_date
     *
     * @param diaryDate the value for tour_diary_t.diary_date
     *
     * @mbggenerated
     */
    public void setDiaryDate(Date diaryDate) {
        this.diaryDate = diaryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour_diary_t.article_id
     *
     * @return the value of tour_diary_t.article_id
     *
     * @mbggenerated
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour_diary_t.article_id
     *
     * @param articleId the value for tour_diary_t.article_id
     *
     * @mbggenerated
     */
    public void setArticleId(String articleId) {
        this.articleId = articleId == null ? null : articleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour_diary_t.diary_level
     *
     * @return the value of tour_diary_t.diary_level
     *
     * @mbggenerated
     */
    public Integer getDiaryLevel() {
        return diaryLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour_diary_t.diary_level
     *
     * @param diaryLevel the value for tour_diary_t.diary_level
     *
     * @mbggenerated
     */
    public void setDiaryLevel(Integer diaryLevel) {
        this.diaryLevel = diaryLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour_diary_t.diary_title
     *
     * @return the value of tour_diary_t.diary_title
     *
     * @mbggenerated
     */
    public String getDiaryTitle() {
        return diaryTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour_diary_t.diary_title
     *
     * @param diaryTitle the value for tour_diary_t.diary_title
     *
     * @mbggenerated
     */
    public void setDiaryTitle(String diaryTitle) {
        this.diaryTitle = diaryTitle == null ? null : diaryTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour_diary_t.diary_city
     *
     * @return the value of tour_diary_t.diary_city
     *
     * @mbggenerated
     */
    public String getDiaryCity() {
        return diaryCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour_diary_t.diary_city
     *
     * @param diaryCity the value for tour_diary_t.diary_city
     *
     * @mbggenerated
     */
    public void setDiaryCity(String diaryCity) {
        this.diaryCity = diaryCity == null ? null : diaryCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour_diary_t.diary_province
     *
     * @return the value of tour_diary_t.diary_province
     *
     * @mbggenerated
     */
    public String getDiaryProvince() {
        return diaryProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour_diary_t.diary_province
     *
     * @param diaryProvince the value for tour_diary_t.diary_province
     *
     * @mbggenerated
     */
    public void setDiaryProvince(String diaryProvince) {
        this.diaryProvince = diaryProvince == null ? null : diaryProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour_diary_t.dairy_country
     *
     * @return the value of tour_diary_t.dairy_country
     *
     * @mbggenerated
     */
    public String getDairyCountry() {
        return dairyCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour_diary_t.dairy_country
     *
     * @param dairyCountry the value for tour_diary_t.dairy_country
     *
     * @mbggenerated
     */
    public void setDairyCountry(String dairyCountry) {
        this.dairyCountry = dairyCountry == null ? null : dairyCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour_diary_t.diary_picture_path
     *
     * @return the value of tour_diary_t.diary_picture_path
     *
     * @mbggenerated
     */
    public String getDiaryPicturePath() {
        return diaryPicturePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour_diary_t.diary_picture_path
     *
     * @param diaryPicturePath the value for tour_diary_t.diary_picture_path
     *
     * @mbggenerated
     */
    public void setDiaryPicturePath(String diaryPicturePath) {
        this.diaryPicturePath = diaryPicturePath == null ? null : diaryPicturePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour_diary_t.diary_picture_name
     *
     * @return the value of tour_diary_t.diary_picture_name
     *
     * @mbggenerated
     */
    public String getDiaryPictureName() {
        return diaryPictureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour_diary_t.diary_picture_name
     *
     * @param diaryPictureName the value for tour_diary_t.diary_picture_name
     *
     * @mbggenerated
     */
    public void setDiaryPictureName(String diaryPictureName) {
        this.diaryPictureName = diaryPictureName == null ? null : diaryPictureName.trim();
    }
}